[tool.poetry]
name = "CalendRuParser"
version = "0.1.0"
description = "Parser for a list of official and unofficial holidays from calend.ru"
authors = ["Sergei Polin <s.polin@innopolis.university>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pytest = "^7.1.3"
flake8 = "^5.0.4"
beautifulsoup4 ="^4.12.2"
certifi = "^2023.5.7"
charset-normalizer = "^3.1.0"
idna = "^3.4"
requests = "^2.31.0"
soupsieve = "^2.4.1"
urllib3 = "^1.26.6"

[tool.poetry.group.dev.dependencies]
mypy = "^0.971"
black = "^22.8.0"
python-semantic-release = "^7.32.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = "pyproject.toml:version" # version location
branch = "main"                             # branch to make releases of
changelog_file = "CHANGELOG.md"             # changelog file
build_command = "poetry build"              # build dists
dist_path = "dist/"                         # where to put dists
upload_to_release = true                    # auto-create GitHub release
upload_to_pypi = false                      # don't auto-upload to PyPI
remove_dist = false                         # don't remove dists
patch_without_tag = true                    # patch release by default