name: Build, Test, Lint, and Publish to PyPI

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Run tests
      run: |
        poetry install
        poetry run pytest

    - name: Run linter
      run: |
        poetry run pylint --exit-zero your_package_name

    - name: Build and Publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry build
        poetry publish
